In [2]:
import pandas as pd


print('Version')

print(pd.__version__)

Version
2.1.1


Series Create, Manipulate,, Query, Delete



In [3]:
print('Create a Pandas Series')

arr = [0,1,2,3,4]       # This is your list called arr

s1 = pd.Series(arr)     # Call this series s1. Series is Capital S
                        # Take this python list and turn it into a Series

print('Index and Array ')

print(s1)       # 2 Rows 1st is index the second is the numbers

Create a Pandas Series
Index and Array 
0    0
1    1
2    2
3    3
4    4
dtype: int64


We are goung to give it some order

In [5]:
print('nOW GIVE THE SERIES AN ORDER STARTING AT 1')

order = [1,2,3,4,5]

s2 = pd.Series(arr,index = order)

print('Index starting at 1 and The array')

print('s2')         # index is now starting at 1
                    # print the series s2



nOW GIVE THE SERIES AN ORDER STARTING AT 1
Index starting at 1 and The array
s2


Look ar numpy
numby creates these random numbers

In [7]:
print('CREATE A PANDAS SERIES OF RANDOM NUMBRS WITH INDEX AS STRING')

import numpy as np

n = np.random.randn(5)      # Create a random Ndarray

index = ['a','b','c','d','e']       #insted of order we call it index. Index does not have to be interger

s2a = pd.Series(n, index = index)

print(s2a)      # index is a,b,c,d,e
                # random numbrrs n 5 Random numbres
                # random number generator

CREATE A PANDAS SERIES OF RANDOM NUMBRS WITH INDEX AS STRING
a    0.285501
b   -0.214111
c   -0.507413
d    0.456125
e   -1.726372
dtype: float64


Creatw a series from a dictionary
a is 1, b is 2
key value pair
like a series
we have created series so far s1,s2,s2a and now s3


In [9]:
print('Series as a Dictionary')

d = {'a':1, 'b':2, 'c':3, 'd':4, 'e':5}     # key value pair

s3 =pd.Series(d)

print(s3)

Series as a Dictionary
a    1
b    2
c    3
d    4
e    5
dtype: int64


Want to print s1 again

Modify the index of the series

In [10]:
print('Want to print S1 again')

print(s1)

Want to print S1 again
0    0
1    1
2    2
3    3
4    4
dtype: int64


Set the index to see below a.b.c.d.e

In [11]:
s1.index = ['A','B','C','D','E']

print(s1)

A    0
B    1
C    2
D    3
E    4
dtype: int64


Slicing section

Viewing s1 not changing it

In [12]:
print('PRINTING THE FIRST 3 ITEMS IN SERIES')


a = s1[:3]

print(a)

PRINTING THE FIRST 3 ITEMS IN SERIES
A    0
B    1
C    2
dtype: int64


In [13]:
print('How far from the End')

a = s1[:-1]     # last 1 missing. How far from the end E 4 is going to be missing

print(a)

How far from the End
A    0
B    1
C    2
D    3
dtype: int64


In [14]:
print('Start from the second one')

a = s1[2:]      # starts at the second one. [C,D,E]

print(a)

Start from the second one
C    2
D    3
E    4
dtype: int64


In [15]:
print('look at the last 2 in the list')

a = s1[-2:]     # looks at the last 2 in list [D,E]

print(a)

look at the last 2 in the list
D    3
E    4
dtype: int64


Appending series

Combining series toghether

In [17]:
print('print S3')       # a,b,c,d,e     1,2,3,4,5

print(s3)

print('Print S1')       # A,B,C,D,E     0,1,2,3,4

print(s1)   

print('Combine S1 and S3 to give S4')

s4 = pd.concat([s1, s3])      # combine into S4   A,B,C,D,E   0,1,2,3,4   a,b,c,d,e   1,2,3,4,5

print(s4)

print S3
a    1
b    2
c    3
d    4
e    5
dtype: int64
Print S1
A    0
B    1
C    2
D    3
E    4
dtype: int64
Combine S1 and S3 to give S4
A    0
B    1
C    2
D    3
E    4
a    1
b    2
c    3
d    4
e    5
dtype: int64


Say want to drop the 'e' from the list



In [18]:
print('Drop/pop the e Fromthe list')

# s4.pop('e') # pops the last one of the list with 'e'

# if you run this statement then this will change s4.
# the e will be dropp from s4

s4 = s4.drop('e')       # this will change s4

print('Pop the Last one')

print('s4 in \n', s4)

Drop/pop the e Fromthe list
Pop the Last one
s4 in 
 A    0
B    1
C    2
D    3
E    4
a    1
b    2
c    3
d    4
dtype: int64


Operation on the series

Create a few arrays

In [20]:
print('Arrays and their index')

arr1 = [0,1,2,3,4,5,7]

arr2 = [6,7,8,9,5]

print('Array 2 with its index')

s5 = pd.Series(arr2)    # automatically assigns the index. A panda series of arr2

print(s5)

Arrays and their index
Array 2 with its index
0    6
1    7
2    8
3    9
4    5
dtype: int64


In [21]:
print('Array 1 with its index')

s6 = pd.Series(arr1)

print(s6)

Array 1 with its index
0    0
1    1
2    2
3    3
4    4
5    5
6    7
dtype: int64


Arrays toghether 
Joining Arrays



In [22]:
print('The 2 Series Together\n\n')

print('Addition')

s7 = s5.add(s6)         # one has more values than other gives null return not error

print(s7)

The 2 Series Together


Addition
0     6.0
1     8.0
2    10.0
3    12.0
4     9.0
5     NaN
6     NaN
dtype: float64


Also subtract

In [23]:
print('Subtraction')

s8 = s5.sub(s6)

print(s8)

Subtraction
0    6.0
1    6.0
2    6.0
3    6.0
4    1.0
5    NaN
6    NaN
dtype: float64


In [24]:
print('Multiply')

s9 = s5.mul(s6)

print(s9)

Multiply
0     0.0
1     7.0
2    16.0
3    27.0
4    20.0
5     NaN
6     NaN
dtype: float64


In [25]:
print('median s6', s6.median())
print('max s6', s6.max())
print('min s6', s6.min())


print('median s9', s9.median())
print('max s9', s9.max())
print('min s9', s9.min())

median s6 3.0
max s6 7
min s6 0
median s9 16.0
max s9 27.0
min s9 0.0


In [26]:
print('Creating a Dataframe')

dates = pd.date_range(start='1/1/2023', end = '1/12/2023', periods = 6)

print(dates)

Creating a Dataframe
DatetimeIndex(['2023-01-01 00:00:00', '2023-01-03 04:48:00',
               '2023-01-05 09:36:00', '2023-01-07 14:24:00',
               '2023-01-09 19:12:00', '2023-01-12 00:00:00'],
              dtype='datetime64[ns]', freq=None)


In [27]:
print('Random Numbers with numpy')

num_arr = np.random.randn(6,4)      # import numpy random array 6 rows a=4 colums

print(num_arr)      # prints the arrat with random numbers

Random Numbers with numpy
[[-0.12486755 -0.41911061 -0.97966994  2.73254315]
 [-2.93754342  0.89491305  0.43377898 -0.58674771]
 [ 0.65360267 -1.32153847 -0.59862625  0.51920132]
 [-0.11528798  0.66452814  0.52932622  0.14821642]
 [ 1.1387238  -0.24748011  0.35759403  0.36742934]
 [-1.52446099  0.74933211 -0.17170135  1.86800215]]


In [31]:
# Create dataframe with dictionary array
# -------------------------------

# Title then a python list.
# Python list [...]

# Title animal, age
# Python list [...]

print('Dataframe with Dictionary Array ')
print()

data = {'animal': ['cat', 'cat', 'snake', 'dog', 'dog', 'cat', 'snake', 'cat', 'dog', 'dog'],
         'age': [2.5, 3.0, 0.5, np.nan, 5, 2, 4.5, np.nan, 7, 3],
         'visits': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
         'priority': ['yes', 'yes', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no']}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

df2 = pd.DataFrame(data, index=labels) # nice table columns and rows

print(df2)

Dataframe with Dictionary Array 

  animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no
d    dog  NaN       3      yes
e    dog  5.0       2       no
f    cat  2.0       3       no
g  snake  4.5       1       no
h    cat  NaN       1      yes
i    dog  7.0       2       no
j    dog  3.0       1       no


THis prints the first 6 values

In [32]:
sh = df2.head(6)

print(sh)

  animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no
d    dog  NaN       3      yes
e    dog  5.0       2       no
f    cat  2.0       3       no


In [33]:
sht = df2.tail(3)

print(sht)

  animal  age  visits priority
h    cat  NaN       1      yes
i    dog  7.0       2       no
j    dog  3.0       1       no


index printing colum printing values printing from data frame


In [34]:
print(df2.index)

print(df2.index)

print(df2.values)

Index(['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j'], dtype='object')
Index(['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j'], dtype='object')
[['cat' 2.5 1 'yes']
 ['cat' 3.0 3 'yes']
 ['snake' 0.5 2 'no']
 ['dog' nan 3 'yes']
 ['dog' 5.0 2 'no']
 ['cat' 2.0 3 'no']
 ['snake' 4.5 1 'no']
 ['cat' nan 1 'yes']
 ['dog' 7.0 2 'no']
 ['dog' 3.0 1 'no']]


describing the data statistically

In [35]:
sdesc = df2.describe()

print(sdesc)

            age     visits
count  8.000000  10.000000
mean   3.437500   1.900000
std    2.007797   0.875595
min    0.500000   1.000000
25%    2.375000   1.000000
50%    3.000000   2.000000
75%    4.625000   2.750000
max    7.000000   3.000000


Transpose the data flips the columns and indexes swap # [Capital T for Transpose]

In [36]:
print('Transpose the data flip the columns with the inexes')


print('\n Transpose Data: \n',df2.T)

Transpose the data flip the columns with the inexes

 Transpose Data: 
             a    b      c    d    e    f      g    h    i    j
animal    cat  cat  snake  dog  dog  cat  snake  cat  dog  dog
age       2.5  3.0    0.5  NaN  5.0  2.0    4.5  NaN  7.0  3.0
visits      1    3      2    3    2    3      1    1    2    1
priority  yes  yes     no  yes   no   no     no  yes   no   no


Sorting data  Sort by age Decending

In [37]:
print('Sroting the data: \n\n')


print('Sort by age: \n')

df3 = df2.sort_values(by='age')

print(df3)

Sroting the data: 


Sort by age: 

  animal  age  visits priority
c  snake  0.5       2       no
f    cat  2.0       3       no
a    cat  2.5       1      yes
b    cat  3.0       3      yes
j    dog  3.0       1       no
g  snake  4.5       1       no
e    dog  5.0       2       no
i    dog  7.0       2       no
d    dog  NaN       3      yes
h    cat  NaN       1      yes


print age and visits

In [39]:
df6 = df2[['age','visits']]

print('Age and visit: \n', df6)

Age and visit: 
    age  visits
a  2.5       1
b  3.0       3
c  0.5       2
d  NaN       3
e  5.0       2
f  2.0       3
g  4.5       1
h  NaN       1
i  7.0       2
j  3.0       1


Copy the dataframe df2 to df13

In [40]:
df13 = df2.copy()

LOOKIN FOR NAN VALUES

wHAT ARE......


In [41]:
df13.isnull()

print('Null values: \n', df13)

Null values: 
   animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no
d    dog  NaN       3      yes
e    dog  5.0       2       no
f    cat  2.0       3       no
g  snake  4.5       1       no
h    cat  NaN       1      yes
i    dog  7.0       2       no
j    dog  3.0       1       no


Everything is false except for a few trues. These are the Nan values

Change the value in the Dataframe where you have Null[NaN] values

Change Age to 1.5 at d location

In [42]:
df13.loc['d','age'] = 1.5

print(df13)

  animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no
d    dog  1.5       3      yes
e    dog  5.0       2       no
f    cat  2.0       3       no
g  snake  4.5       1       no
h    cat  NaN       1      yes
i    dog  7.0       2       no
j    dog  3.0       1       no


mean values

Mean values of age in df13



In [44]:
df13[['age']].mean()    #age 3.375

df13a = df13[['age']].mean()

print('The mean age is ', df13a)



print('Mean of age and visits')

df13m = df13.mean()

print(df13m)

The mean age is  age    3.222222
dtype: float64
Mean of age and visits


TypeError: Could not convert ['catcatsnakedogdogcatsnakecatdogdog' 'yesyesnoyesnononoyesnono'] to numeric

sum of values, minuimun values....

In [45]:
df13s = df13['visits'].sum()

print('sum of vistis: ',df13s)


df13min = df13['visits'].min()

print('min', df13min)

df13ma = df13['visits'].max()

print('max',df13ma)

sum of vistis:  19
min 1
max 3
